ORG 100H

MOV AL, 0FH       ; HEX=0FH=DEC15  
MOV BL, 0EH      ; HEX=0EH=DEC14

ADD BL,AL

MOV CX, 8
PRINT: MOV AH, 2   ; PRINT FUNCTION. INTERUPT ER SUBFUNCTION
       MOV DL, '0'
       TEST BL, 10000000B  ; TEST FIRST BIT.
       JZ ZERO
       MOV DL, '1'
ZERO:  INT 21H; FIND INTERUPT  SUBFUNCTION
       SHL BL, 1
LOOP PRINT

; PRINT HEXA SUFFIX:
MOV DL, 'H'
INT 21H

; WAIT FOR ANY KEY PRESS:
MOV AH, 0
INT 16H
RET