.MODEL SMALL
.STACK 100H
.DATA
MSGGR DB ' YES $'
MSGLS DB ' NO $'
.CODE
MAIN PROC
MOV AX, @DATA
MOV DS, AX

MOV AL, 3     ; INPUT FIRST NUMBER
INT 21H
MOV BL, AL     ; SAVING FIRST NUMBER TO BL FROM AL

MOV AL, 7      ; INPUT SECOND NUMBER
INT 21H
MOV CL, AL    ; SAVING SECOND NUMBER TO CL FROM AL

CMP BL, CL          ; COMPARE TO CHECK THE FIRST IS GREATER OR LESSER
JGE GREATER         ; IF GREATER, JUMP TO GREATER TO PRINT A GREATER MSG

MOV DX, OFFSET MSGLS  ; BUT IF NOT GREATER, PRINT LESSER MSG
MOV AH,9
INT 21H
JMP PRINT

GREATER:
MOV DX, OFFSET MSGGR
MOV AH,9
INT 21H
JMP PRINT

PRINT:
MOV AH,4CH
INT 21H
MAIN ENDP

END MAIN
